### ISSUE TITLE
Call on Windows fails

### ISSUE THREAD

**Issue by mrx23dot** [tpircher/pycrc#2]
```
python3 -m pip install pycrc
Collecting pycrc
  Downloading pycrc-0.10.0-py3-none-any.whl (33 kB)
Installing collected packages: pycrc
Successfully installed pycrc-0.10.0
```

```
λ pycrc
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pycrc.exe\__main__.py", line 4, in <module>
  File "C:\Python37\lib\site-packages\pycrc\__init__.py", line 1, in <module>
    import importlib.metadata
ModuleNotFoundError: No module named 'importlib.metadata'
```
Python 3.7.0

**Comment by tpircher** [comment]
I have updated the requirements in the pyproject.toml file.
You can also manually install importlib.metadata with `pip install importlib-metadata` or `pip3 install importlib-metadata`
